# Generated by Django 5.2.5 on 2025-09-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_featured',
            new_name='is_best_seller',
        ),
    ]
